# deploy
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-jenkins
spec:
  replicas: 3
  selector:
    matchLabels:
      page: jenkins-label
  template:
    metadata:
      name: pod-jenkins
      labels:
        page: jenkins-label
    spec:
      containers:
      - name: ctn-jenkins
        image: nginx
        ports:
        - containerPort: 80
---
# service
apiVersion: v1
kind: Service
metadata:
  name: jenkins-lb
spec:
  ports:
  - name: jenkins-port
    targetPort: 80
    port: 80
  selector:
    page: jenkins-label
  type: LoadBalancer
